IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_BUNDLE_PRODUCTS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_BUNDLE_PRODUCTS] (
        [PMT_BUNDLES_ID] numeric(28,0) NOT NULL,
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_RFA_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_RFA_FILES] (
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_APPROVAL_REQUESTS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_APPROVAL_REQUESTS] (
        [PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [CLIENT_UNIT] varchar(255),
        [REQUESTOR_TYPE] varchar(255),
        [COMMITTEE] varchar(255),
        [LEGACY] varchar(5),
        [PRODUCT_MANAGER] varchar(255),
        [REVIEW_OF_RFA_ID] numeric(28,0),
        [ISREVIEW] bit,
        [STATUS] varchar(60),
        [USERNAME] varchar(30),
        [CREATION_TIMESTAMP] datetime,
        [UPDATE_TIMESTAMP] datetime,
        [APPROVAL_DATE] datetime,
        [NEXT_REVIEW_DATE] datetime,
        [ARCHIVED] bit,
        [CLIENT_SEGMENT] varchar(750),
        PRIMARY KEY ([PMT_APPROVAL_REQUESTS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_FEATURES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_FEATURES] (
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL,
        [FEATURE_NAME] varchar(300),
        [FEATURE_VALUE] varchar(300)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITION_BUNDLES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITION_BUNDLES] (
        [PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL,
        [PMT_BUNDLES_PMT_BUNDLES_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_BUNDLE_APPROVALS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_BUNDLE_APPROVALS] (
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [PMT_BUNDLES_PMT_BUNDLES_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PRODUCT_IDENTIFIERS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PRODUCT_IDENTIFIERS] (
        [PRODUCT_IDENTIFIERS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [PRODUCT_ID] numeric(28,0),
        [PRODUCT_NAME] varchar(255),
        [PRODUCT_IDENTIFICATION_CODE] varchar(60),
        [STATUS] varchar(60),
        [AML_INTEGRITY_RISK] varchar(30),
        [FINANCING_OF_TERRORISM_RISK] varchar(30),
        [GLOBAL_PRODUCT_ID] numeric(28,0),
        [GLOBAL_PRODUCT_NAME] varchar(255),
        PRIMARY KEY ([PRODUCT_IDENTIFIERS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_MEETINGS_RFA' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_MEETINGS_RFA] (
        [PMT_MEETINGS_PMT_MEETINGS_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITIONS_ASSOCIATION' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITIONS_ASSOCIATION] (
        [PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL,
        [ASSOCIATED_PROPOSITION_ID] numeric(28,0)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_FILES_ATTRIBUTES_MAP' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_FILES_ATTRIBUTES_MAP] (
        [FILES_ATTRIBUTES_ID] numeric(28,0) NOT NULL,
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [FIELD_NAME] varchar(255),
        PRIMARY KEY ([FILES_ATTRIBUTES_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CLIENT_UNITS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CLIENT_UNITS] (
        [PMT_CLIENT_UNITS_NAME] varchar(255) NOT NULL,
        [LABEL] varchar(255),
        [ISARCHIVED] bit,
        PRIMARY KEY ([PMT_CLIENT_UNITS_NAME])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_COMMITTEES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_COMMITTEES] (
        [PMT_COMMITTEES_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [COMMITTEE_NAME] varchar(255),
        [CLIENT_UNIT_NAME] varchar(255) NOT NULL,
        [LABEL] varchar(255),
        [ISGLOBAL] bit,
        [ISARCHIVED] bit,
        [CLIENT_UNIT_NAME1] varchar(255),
        PRIMARY KEY ([PMT_COMMITTEES_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CLIENT_SEGMENT_COMMITTEE_MAP' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CLIENT_SEGMENT_COMMITTEE_MAP] (
        [PMT_COMMITTEES_ID] numeric(28,0) NOT NULL,
        [CLIENT_SEGMENT_NAME] varchar(600),
        [COMMITTEE_NAME] varchar(600)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITION_APPROVALS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITION_APPROVALS] (
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CONFIG_FIELDS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CONFIG_FIELDS] (
        [NAME] varchar(255) NOT NULL,
        [LABEL] varchar(1500),
        [DESCRIPTION] text,
        [TYPE] varchar(50),
        [PARENT] varchar(255),
        [TOPIC] varchar(255),
        [STORAGE_TABLE] varchar(255),
        [CONFIG] text,
        [SORT_ORDER] numeric(28,0),
        [GUIDELINES] text,
        PRIMARY KEY ([NAME])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITIONS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITIONS] (
        [PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [PROPOSITION_NAME] varchar(255),
        [PROPOSITION_OWNER] varchar(255),
        [STATUS] varchar(60),
        [CREATION_TIMESTAMP] datetime,
        [INTRODUCTION_TIMESTAMP] datetime,
        [UPDATE_TIMESTAMP] datetime,
        [RETIREMENT_TIMESTAMP] datetime,
        PRIMARY KEY ([PMT_PROPOSITIONS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_ASSIGNED_COMMITTEES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_ASSIGNED_COMMITTEES] (
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [PMT_COMMITTEES_PMT_COMMITTEES_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_BUNDLES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_BUNDLES] (
        [PMT_BUNDLES_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [BUNDLE_NAME] varchar(255),
        [BUNDLE_OWNER] varchar(255),
        [STATUS] varchar(60),
        [CREATION_TIMESTAMP] datetime,
        [INTRODUCTION_TIMESTAMP] datetime,
        [UPDATE_TIMSTAMP] datetime,
        [RETIREMENT_TIMESTAMP] datetime,
        PRIMARY KEY ([PMT_BUNDLES_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_USER_PROFILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_USER_PROFILES] (
        [USER_ID] varchar(30) NOT NULL,
        [FULL_NAME] varchar(255),
        [EMAIL] varchar(255),
        [ISARCHIVED] bit NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CONFIG_FORMS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CONFIG_FORMS] (
        [NAME] varchar(255) NOT NULL,
        [REQUESTOR_TYPE] varchar(255),
        [ISLEGACY] bit,
        [LABEL] varchar(255),
        [DESCRIPTION] varchar(255),
        [ISARCHIVED] bit,
        PRIMARY KEY ([NAME])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PRODUCT_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PRODUCT_FILES] (
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_PRODUCTS_PMT_PRODUCTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_MEETINGS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_MEETINGS] (
        [PMT_MEETINGS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [PMT_COMMITTEES_ID] numeric(28,0) NOT NULL,
        [APPROVING_COMMITTEE] varchar(255),
        [MEETING_DATE] datetime,
        [USERNAME] varchar(30),
        [LAST_UPDATED] datetime,
        PRIMARY KEY ([PMT_MEETINGS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_BUNDLE_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_BUNDLE_FILES] (
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_BUNDLES_PMT_BUNDLES_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_TOPICS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_TOPICS] (
        [PMT_TOPICS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [NAME] varchar(255),
        PRIMARY KEY ([PMT_TOPICS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITION_PRODUCTS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITION_PRODUCTS] (
        [PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL,
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PRODUCTS_ASSOCIATION' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PRODUCTS_ASSOCIATION] (
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL,
        [ASSOCIATED_PRODUCT_ID] numeric(28,0)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_FILES] (
        [DOCUMENT_ID] numeric(28,0) NOT NULL,
        [FILENAME] varchar(500),
        [MIMETYPE] varchar(255),
        [FILESIZE] numeric(28,0),
        [DATA] varbinary(1),
        [DESCRIPTION] text,
        [DOCUMENT_TYPE] varchar(255),
        [USERNAME] varchar(30),
        [UPLOAD_TIMESTAMP] datetime,
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [PMT_MEETINGS_PMT_MEETINGS_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID2] numeric(28,0) NOT NULL,
        [PMT_MEETINGS_PMT_MEETINGS_ID2] numeric(28,0) NOT NULL,
        PRIMARY KEY ([DOCUMENT_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_TOPIC_ATTRIBUTES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_TOPIC_ATTRIBUTES] (
        [PMT_TOPIC_ATTRIBUTES_ID] numeric(28,0) NOT NULL,
        [PMT_TOPICS_ID] numeric(28,0) NOT NULL,
        [NAME] varchar(255),
        [DATA] text,
        [USERNAME] varchar(30),
        [UPDATE_TIMESTAMP] datetime,
        PRIMARY KEY ([PMT_TOPIC_ATTRIBUTES_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CLIENT_SEGMENTS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CLIENT_SEGMENTS] (
        [NAME] varchar(600) NOT NULL,
        [LABEL] varchar(600)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_COMMITTEE_USER_MAP' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_COMMITTEE_USER_MAP] (
        [PMT_COMMITTEES_ID] numeric(28,0) NOT NULL,
        [COMMITTEE_NAME] varchar(255),
        [USER_ID] varchar(255)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_AUDIT' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_AUDIT] (
        [PMT_AUDIT_ID] numeric(28,0) NOT NULL,
        [ORIGIN_ID] numeric(28,0),
        [ORIGIN_PARENT_ID] numeric(28,0),
        [REVISION] numeric(28,0),
        [ORIGIN_NAME] varchar(255),
        [FIELD] varchar(255),
        [FIELD_TYPE] varchar(255),
        [FIELD_LABEL] varchar(255),
        [DATA] text,
        [USERNAME] varchar(30),
        [UPDATE_TIMESTAMP] datetime,
        PRIMARY KEY ([PMT_AUDIT_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CONDITIONS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CONDITIONS] (
        [PMT_CONDITIONS_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL,
        [DESCRIPTION] text,
        [OWNER] varchar(255),
        [DUE_DATE] datetime,
        [STATUS] varchar(30),
        [USERNAME] varchar(30),
        [CLOSED_DATE] datetime,
        [COMMENTS] text,
        [RISK_TAXONOMY] varchar(255),
        [GENERIC_RISK] varchar(255),
        [SECOND_LINE] varchar(100),
        [COUNTRIES] varchar(300),
        PRIMARY KEY ([PMT_CONDITIONS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_STATIC_DATA' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_STATIC_DATA] (
        [DATA_LABEL] varchar(600),
        [DATA_VALUE] varchar(255),
        [SORT_ORDER] numeric(28,0),
        [PARENT_DATA_VALUE] varchar(255),
        [ISARCHIVED] bit
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PRODUCT_APPROVALS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PRODUCT_APPROVALS] (
        [PMT_PRODUCTS_PMT_PRODUCTS_ID] numeric(28,0) NOT NULL,
        [PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_MEETING_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_MEETING_FILES] (
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_MEETINGS_PMT_MEETINGS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_BUNDLES_ASSOCIATION' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_BUNDLES_ASSOCIATION] (
        [PMT_BUNDLES_ID] numeric(28,0) NOT NULL,
        [ASSOCIATED_BUNDLE_ID] numeric(28,0)
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PROPOSITION_FILES' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PROPOSITION_FILES] (
        [PMT_FILES_DOCUMENT_ID] numeric(28,0) NOT NULL,
        [PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID] numeric(28,0) NOT NULL
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_CONFIG_FORM_FIELD_MAP' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_CONFIG_FORM_FIELD_MAP] (
        [FORM_FIELD_MAP_ID] numeric(28,0) NOT NULL,
        [FORM_NAME] varchar(255),
        [FIELD_NAME] varchar(255),
        [ROLE] varchar(255),
        [STATUS] varchar(100),
        [DISPLAY_MODE] numeric(28,0),
        PRIMARY KEY ([FORM_FIELD_MAP_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_PRODUCTS' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_PRODUCTS] (
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL IDENTITY(1,1),
        [PRODUCT_NAME] varchar(255),
        [CLASS_GROUP] varchar(100),
        [CLASS_CAT_PRIMARY] varchar(100),
        [CLASS_CAT_SECONDARY] varchar(100),
        [CLASS_CAT_TERTIARY] varchar(100),
        [LISTED_UNLISTED] varchar(30),
        [MANUFACTURER_INT_EXT] varchar(30),
        [MANUFACTURER_LEGAL_ENTITIES] varchar(255),
        [MANUFACTURER_LABEL] varchar(255),
        [MANUFACTURER_PRODUCT_OWNER] varchar(255),
        [INTRODUCTION_DATE] datetime,
        [MATURITY_DATE] datetime,
        [INVALIDITY_DATE] datetime,
        [CURRENCY] varchar(30),
        [STATUS] varchar(60),
        [USERNAME] varchar(30),
        [CREATE_TIMESTAMP] datetime,
        [UPDATE_TIMESTAMP] datetime,
        [AML_INTEGRITY_RISK] varchar(30),
        [FINANCING_OF_TERRORISM_RISK] varchar(30),
        [SANCTIONS_RISK] varchar(30),
        [IFRS_AND_REGULATORY_TREATMENT] varchar(30),
        [SOURCE_APPLICATION] varchar(10),
        [PMT_PRODUCT_IDENTIFIERS_ID] numeric(28,0) NOT NULL,
        PRIMARY KEY ([PMT_PRODUCTS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'PMT_ANDES_DATA' AND xtype = 'U')
BEGIN
    CREATE TABLE [pmt_owner].[PMT_ANDES_DATA] (
        [ANDES_ID] numeric(18,0) NOT NULL IDENTITY(1,1),
        [ANDES_UPDATE_PRODUCT_DATA] nvarchar(max),
        [SYNCED_WITH_ANDES] bit,
        [PMT_PRODUCTS_ID] numeric(28,0) NOT NULL,
        PRIMARY KEY ([PMT_PRODUCTS_ID])
    );
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_PRODUCTS_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_PRODUCTS]
        ADD CONSTRAINT [PMT_BUNDLE_PRODUCTS_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_PRODUCTS_PMT_BUNDLES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_PRODUCTS]
        ADD CONSTRAINT [PMT_BUNDLE_PRODUCTS_PMT_BUNDLES_FK]
        FOREIGN KEY ([PMT_BUNDLES_ID]) 
        REFERENCES [pmt_owner].[PMT_BUNDLES]([PMT_BUNDLES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_RFA_FILES_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_RFA_FILES]
        ADD CONSTRAINT [PMT_RFA_FILES_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_RFA_FILES_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_RFA_FILES]
        ADD CONSTRAINT [PMT_RFA_FILES_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_FEATURES_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_FEATURES]
        ADD CONSTRAINT [PMT_FEATURES_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_BUNDLES_PMT_PROPOSITIONS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_BUNDLES]
        ADD CONSTRAINT [PMT_PROPOSITION_BUNDLES_PMT_PROPOSITIONS_FK]
        FOREIGN KEY ([PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID]) 
        REFERENCES [pmt_owner].[PMT_PROPOSITIONS]([PMT_PROPOSITIONS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_BUNDLES_PMT_BUNDLES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_BUNDLES]
        ADD CONSTRAINT [PMT_PROPOSITION_BUNDLES_PMT_BUNDLES_FK]
        FOREIGN KEY ([PMT_BUNDLES_PMT_BUNDLES_ID]) 
        REFERENCES [pmt_owner].[PMT_BUNDLES]([PMT_BUNDLES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_APPROVALS_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_APPROVALS]
        ADD CONSTRAINT [PMT_BUNDLE_APPROVALS_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_APPROVALS_PMT_BUNDLES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_APPROVALS]
        ADD CONSTRAINT [PMT_BUNDLE_APPROVALS_PMT_BUNDLES_FK]
        FOREIGN KEY ([PMT_BUNDLES_PMT_BUNDLES_ID]) 
        REFERENCES [pmt_owner].[PMT_BUNDLES]([PMT_BUNDLES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_MEETINGS_RFA_PMT_MEETINGS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_MEETINGS_RFA]
        ADD CONSTRAINT [PMT_MEETINGS_RFA_PMT_MEETINGS_FK]
        FOREIGN KEY ([PMT_MEETINGS_PMT_MEETINGS_ID]) 
        REFERENCES [pmt_owner].[PMT_MEETINGS]([PMT_MEETINGS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_MEETINGS_RFA_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_MEETINGS_RFA]
        ADD CONSTRAINT [PMT_MEETINGS_RFA_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITIONS_ASSOCIATION_PMT_PROPOSITIONS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITIONS_ASSOCIATION]
        ADD CONSTRAINT [PMT_PROPOSITIONS_ASSOCIATION_PMT_PROPOSITIONS_FK]
        FOREIGN KEY ([PMT_PROPOSITIONS_ID]) 
        REFERENCES [pmt_owner].[PMT_PROPOSITIONS]([PMT_PROPOSITIONS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_FILES_ATTRIBUTES_MAP_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_FILES_ATTRIBUTES_MAP]
        ADD CONSTRAINT [PMT_FILES_ATTRIBUTES_MAP_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_FILES_ATTRIBUTES_MAP_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_FILES_ATTRIBUTES_MAP]
        ADD CONSTRAINT [PMT_FILES_ATTRIBUTES_MAP_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_COMMITTEES_PMT_CLIENT_UNITS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_COMMITTEES]
        ADD CONSTRAINT [PMT_COMMITTEES_PMT_CLIENT_UNITS_FK]
        FOREIGN KEY ([CLIENT_UNIT_NAME]) 
        REFERENCES [pmt_owner].[PMT_CLIENT_UNITS]([PMT_CLIENT_UNITS_NAME])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_CLIENT_SEGMENT_COMMITTEE_MAP_PMT_COMMITTEES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_CLIENT_SEGMENT_COMMITTEE_MAP]
        ADD CONSTRAINT [PMT_CLIENT_SEGMENT_COMMITTEE_MAP_PMT_COMMITTEES_FK]
        FOREIGN KEY ([PMT_COMMITTEES_ID]) 
        REFERENCES [pmt_owner].[PMT_COMMITTEES]([PMT_COMMITTEES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_APPROVALS_PMT_PROPOSITIONS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_APPROVALS]
        ADD CONSTRAINT [PMT_PROPOSITION_APPROVALS_PMT_PROPOSITIONS_FK]
        FOREIGN KEY ([PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID]) 
        REFERENCES [pmt_owner].[PMT_PROPOSITIONS]([PMT_PROPOSITIONS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_APPROVALS_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_APPROVALS]
        ADD CONSTRAINT [PMT_PROPOSITION_APPROVALS_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_ASSIGNED_COMMITTEES_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_ASSIGNED_COMMITTEES]
        ADD CONSTRAINT [PMT_ASSIGNED_COMMITTEES_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_ASSIGNED_COMMITTEES_PMT_COMMITTEES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_ASSIGNED_COMMITTEES]
        ADD CONSTRAINT [PMT_ASSIGNED_COMMITTEES_PMT_COMMITTEES_FK]
        FOREIGN KEY ([PMT_COMMITTEES_PMT_COMMITTEES_ID]) 
        REFERENCES [pmt_owner].[PMT_COMMITTEES]([PMT_COMMITTEES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCT_FILES_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCT_FILES]
        ADD CONSTRAINT [PMT_PRODUCT_FILES_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCT_FILES_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCT_FILES]
        ADD CONSTRAINT [PMT_PRODUCT_FILES_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_MEETINGS_PMT_COMMITTEES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_MEETINGS]
        ADD CONSTRAINT [PMT_MEETINGS_PMT_COMMITTEES_FK]
        FOREIGN KEY ([PMT_COMMITTEES_ID]) 
        REFERENCES [pmt_owner].[PMT_COMMITTEES]([PMT_COMMITTEES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_FILES_PMT_BUNDLES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_FILES]
        ADD CONSTRAINT [PMT_BUNDLE_FILES_PMT_BUNDLES_FK]
        FOREIGN KEY ([PMT_BUNDLES_PMT_BUNDLES_ID]) 
        REFERENCES [pmt_owner].[PMT_BUNDLES]([PMT_BUNDLES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLE_FILES_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLE_FILES]
        ADD CONSTRAINT [PMT_BUNDLE_FILES_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_TOPICS_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_TOPICS]
        ADD CONSTRAINT [PMT_TOPICS_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_PRODUCTS_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_PRODUCTS]
        ADD CONSTRAINT [PMT_PROPOSITION_PRODUCTS_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_PRODUCTS_PMT_PROPOSITIONS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_PRODUCTS]
        ADD CONSTRAINT [PMT_PROPOSITION_PRODUCTS_PMT_PROPOSITIONS_FK]
        FOREIGN KEY ([PMT_PROPOSITIONS_ID]) 
        REFERENCES [pmt_owner].[PMT_PROPOSITIONS]([PMT_PROPOSITIONS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCTS_ASSOCIATION_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCTS_ASSOCIATION]
        ADD CONSTRAINT [PMT_PRODUCTS_ASSOCIATION_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_TOPIC_ATTRIBUTES_PMT_TOPICS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_TOPIC_ATTRIBUTES]
        ADD CONSTRAINT [PMT_TOPIC_ATTRIBUTES_PMT_TOPICS_FK]
        FOREIGN KEY ([PMT_TOPICS_ID]) 
        REFERENCES [pmt_owner].[PMT_TOPICS]([PMT_TOPICS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_COMMITTEE_USER_MAP_PMT_COMMITTEES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_COMMITTEE_USER_MAP]
        ADD CONSTRAINT [PMT_COMMITTEE_USER_MAP_PMT_COMMITTEES_FK]
        FOREIGN KEY ([PMT_COMMITTEES_ID]) 
        REFERENCES [pmt_owner].[PMT_COMMITTEES]([PMT_COMMITTEES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_CONDITIONS_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_CONDITIONS]
        ADD CONSTRAINT [PMT_CONDITIONS_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCT_APPROVALS_PMT_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCT_APPROVALS]
        ADD CONSTRAINT [PMT_PRODUCT_APPROVALS_PMT_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCT_APPROVALS_PMT_APPROVAL_REQUESTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCT_APPROVALS]
        ADD CONSTRAINT [PMT_PRODUCT_APPROVALS_PMT_APPROVAL_REQUESTS_FK]
        FOREIGN KEY ([PMT_APPROVAL_REQUESTS_PMT_APPROVAL_REQUESTS_ID]) 
        REFERENCES [pmt_owner].[PMT_APPROVAL_REQUESTS]([PMT_APPROVAL_REQUESTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_MEETING_FILES_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_MEETING_FILES]
        ADD CONSTRAINT [PMT_MEETING_FILES_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_MEETING_FILES_PMT_MEETINGS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_MEETING_FILES]
        ADD CONSTRAINT [PMT_MEETING_FILES_PMT_MEETINGS_FK]
        FOREIGN KEY ([PMT_MEETINGS_PMT_MEETINGS_ID]) 
        REFERENCES [pmt_owner].[PMT_MEETINGS]([PMT_MEETINGS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_BUNDLES_ASSOCIATION_PMT_BUNDLES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_BUNDLES_ASSOCIATION]
        ADD CONSTRAINT [PMT_BUNDLES_ASSOCIATION_PMT_BUNDLES_FK]
        FOREIGN KEY ([PMT_BUNDLES_ID]) 
        REFERENCES [pmt_owner].[PMT_BUNDLES]([PMT_BUNDLES_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_FILES_PMT_PROPOSITIONS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_FILES]
        ADD CONSTRAINT [PMT_PROPOSITION_FILES_PMT_PROPOSITIONS_FK]
        FOREIGN KEY ([PMT_PROPOSITIONS_PMT_PROPOSITIONS_ID]) 
        REFERENCES [pmt_owner].[PMT_PROPOSITIONS]([PMT_PROPOSITIONS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PROPOSITION_FILES_PMT_FILES_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PROPOSITION_FILES]
        ADD CONSTRAINT [PMT_PROPOSITION_FILES_PMT_FILES_FK]
        FOREIGN KEY ([PMT_FILES_DOCUMENT_ID]) 
        REFERENCES [pmt_owner].[PMT_FILES]([DOCUMENT_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_PRODUCTS_PMT_PRODUCT_IDENTIFIERS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_PRODUCTS]
        ADD CONSTRAINT [PMT_PRODUCTS_PMT_PRODUCT_IDENTIFIERS_FK]
        FOREIGN KEY ([PMT_PRODUCT_IDENTIFIERS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCT_IDENTIFIERS]([PRODUCT_IDENTIFIERS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;


IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'PMT_ANDES_PRODUCTS_FK')
BEGIN 
    ALTER TABLE [pmt_owner].[PMT_ANDES_DATA]
        ADD CONSTRAINT [PMT_ANDES_PRODUCTS_FK]
        FOREIGN KEY ([PMT_PRODUCTS_ID]) 
        REFERENCES [pmt_owner].[PMT_PRODUCTS]([PMT_PRODUCTS_ID])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
END;
